### ISSUE TITLE
RSI bug

### ISSUE THREAD

**Issue by IvanJames94** [e-milho/trality#1]
https://github.com/e-milho/trality/blob/20847d97c5730ea558a2d6620e34fc8bc47535f4/multicoin_accumulator.py#L254

There is an error with the RSI. If you want the last 3 bars, this is how you do it:
    # get RSI of last 3 bars
    rsi3 = data.close.rsi(14)[-3] #third from last
    rsi2 = data.close.rsi(14)[-2] #second from last
    rsi1 = data.close.rsi(14)[-1] #last bar

The RSI data object can have around 50-80 values in it, depending on your window size in the schedule.
You have a window size of 80 so the RSI is 67 values long. 
data.close.rsi(14)[**0**] gets you the first value in the RSI or the 67th from last.

The new version looks awesome. Keep up the good work.

**Comment by e-milho** [comment]
Thanks! Hey you should join the Discord channel if you haven't already

**Comment by e-milho** [comment]
Fixed! 
(the other way around, rsi3 being the last bar, but that order doesn't really matter for the calculation)
Thanks for pointing this out.
